# Nome do projeto (para logs do Spring Boot)
spring.application.name=SALF_Backend

# Porta do servidor
server.port=8080

# Configuração customizada para o SingletonDB (não gerenciada pelo Spring)
# Apenas para referência, pois a conexão é feita manualmente
db.url=jdbc:postgresql://localhost:5432/salf_db
db.username=postgres
db.password=postgres

# Logs
logging.level.root=INFO
logging.level.projeto.salf=DEBUG

#spring.web.resources.static-locations=classpath:/static/,file:frontend/

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.mvc.static-path-pattern=/resources/**
