-- MySQL Script generated by MySQL Workbench
-- Thu Oct 16 19:18:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `Func_Cpf` VARCHAR(14) NOT NULL,
  `Func_Nome` VARCHAR(60) NOT NULL,
  `Func_Senha` VARCHAR(20) NOT NULL,
  `Func_Email` VARCHAR(30) NOT NULL,
  `Func_Telefone` VARCHAR(20) NOT NULL,
  `Tipo_Acesso` INT NOT NULL,
  `DataAdmissao` DATE NOT NULL,
  `DataDemissao` DATE NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `UserName` VARCHAR(20) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `CEP` VARCHAR(10) NOT NULL,
  `Cargp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Func_Cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CategoriaProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CategoriaProduto` (
  `Cat_Cod` INT NOT NULL,
  `Cat_Descr` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Cat_Cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `Prod_Cod` INT NOT NULL,
  `Prod_Descr` VARCHAR(100) NOT NULL,
  `CategoriaProduto_Cat_Cod` INT NOT NULL,
  PRIMARY KEY (`Prod_Cod`),
  INDEX `fk_Produto_CategoriaProduto1_idx` (`CategoriaProduto_Cat_Cod` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_CategoriaProduto1`
    FOREIGN KEY (`CategoriaProduto_Cat_Cod`)
    REFERENCES `mydb`.`CategoriaProduto` (`Cat_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ListaCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ListaCompra` (
  `Lc_Cod` INT NOT NULL,
  `Funcionario_Func_Cpf` VARCHAR(18) NOT NULL,
  `DataCriacao` DATE NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `StatusAtendimento` INT NOT NULL,
  `Funcionario_Func_Cpf1` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`Lc_Cod`, `Funcionario_Func_Cpf`),
  INDEX `fk_ListaCompra_Funcionario1_idx` (`Funcionario_Func_Cpf1` ASC) VISIBLE,
  CONSTRAINT `fk_ListaCompra_Funcionario1`
    FOREIGN KEY (`Funcionario_Func_Cpf1`)
    REFERENCES `mydb`.`Funcionario` (`Func_Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `Est_Cod` INT NOT NULL,
  `Est_ProdQuantidade` INT NOT NULL,
  `DataValidade` DATE NOT NULL,
  `Produto_Prod_Cod` INT NOT NULL,
  PRIMARY KEY (`Est_Cod`),
  INDEX `fk_Estoque_Produto1_idx` (`Produto_Prod_Cod` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Produto1`
    FOREIGN KEY (`Produto_Prod_Cod`)
    REFERENCES `mydb`.`Produto` (`Prod_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CestaBasica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CestaBasica` (
  `CB_Cod` INT NOT NULL,
  `Descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CB_Cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CestaBasica_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CestaBasica_has_Produto` (
  `CestaBasica_CB_Cod` INT NOT NULL,
  `Produto_Prod_Cod` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`CestaBasica_CB_Cod`, `Produto_Prod_Cod`),
  INDEX `fk_CestaBasica_has_Produto_Produto1_idx` (`Produto_Prod_Cod` ASC) VISIBLE,
  INDEX `fk_CestaBasica_has_Produto_CestaBasica1_idx` (`CestaBasica_CB_Cod` ASC) VISIBLE,
  CONSTRAINT `fk_CestaBasica_has_Produto_CestaBasica1`
    FOREIGN KEY (`CestaBasica_CB_Cod`)
    REFERENCES `mydb`.`CestaBasica` (`CB_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CestaBasica_has_Produto_Produto1`
    FOREIGN KEY (`Produto_Prod_Cod`)
    REFERENCES `mydb`.`Produto` (`Prod_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(20) NOT NULL,
  `Contato` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cotacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cotacao` (
  `idCotacao` INT NOT NULL,
  `DataAbertura` DATE NOT NULL,
  `DataFechamento` DATE NOT NULL,
  PRIMARY KEY (`idCotacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FornecCotacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FornecCotacao` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Cotacao_idCotacao` INT NOT NULL,
  `StatusRealizou` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Cotacao_idCotacao`),
  INDEX `fk_Fornecedor_has_Cotacao_Cotacao1_idx` (`Cotacao_idCotacao` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Cotacao_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Cotacao_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Cotacao_Cotacao1`
    FOREIGN KEY (`Cotacao_idCotacao`)
    REFERENCES `mydb`.`Cotacao` (`idCotacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `Compra_Cod` INT NOT NULL,
  `Compra_ValorTT` FLOAT NOT NULL,
  `DataCompra` DATE NOT NULL,
  `FornecCotacao_Fornecedor_idFornecedor` INT NOT NULL,
  `FornecCotacao_Cotacao_idCotacao` INT NOT NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Funcionario_Func_Cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`Compra_Cod`),
  INDEX `fk_Compra_FornecCotacao1_idx` (`FornecCotacao_Fornecedor_idFornecedor` ASC, `FornecCotacao_Cotacao_idCotacao` ASC) VISIBLE,
  INDEX `fk_Compra_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  INDEX `fk_Compra_Funcionario1_idx` (`Funcionario_Func_Cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_FornecCotacao1`
    FOREIGN KEY (`FornecCotacao_Fornecedor_idFornecedor` , `FornecCotacao_Cotacao_idCotacao`)
    REFERENCES `mydb`.`FornecCotacao` (`Fornecedor_idFornecedor` , `Cotacao_idCotacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Funcionario1`
    FOREIGN KEY (`Funcionario_Func_Cpf`)
    REFERENCES `mydb`.`Funcionario` (`Func_Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaCarente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaCarente` (
  `PC_Cpf` VARCHAR(14) NOT NULL,
  `PC_Nome` VARCHAR(60) NOT NULL,
  `PC_DataNasc` DATE NOT NULL,
  `PC_TELEFONE` VARCHAR(20) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`PC_Cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doação` (
  `Doa_Cod` INT NOT NULL,
  `PessoaCarente_PC_Cpf` VARCHAR(18) NOT NULL,
  `Data` DATE NOT NULL,
  `Observacao` VARCHAR(100) NULL,
  PRIMARY KEY (`Doa_Cod`),
  INDEX `fk_Doação_PessoaCarente1_idx` (`PessoaCarente_PC_Cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Doação_PessoaCarente1`
    FOREIGN KEY (`PessoaCarente_PC_Cpf`)
    REFERENCES `mydb`.`PessoaCarente` (`PC_Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doação_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doação_has_Produto` (
  `Doação_Doa_Cod` INT NOT NULL,
  `Produto_Prod_Cod` INT NOT NULL,
  PRIMARY KEY (`Doação_Doa_Cod`, `Produto_Prod_Cod`),
  INDEX `fk_Doação_has_Produto_Produto1_idx` (`Produto_Prod_Cod` ASC) VISIBLE,
  INDEX `fk_Doação_has_Produto_Doação1_idx` (`Doação_Doa_Cod` ASC) VISIBLE,
  CONSTRAINT `fk_Doação_has_Produto_Doação1`
    FOREIGN KEY (`Doação_Doa_Cod`)
    REFERENCES `mydb`.`Doação` (`Doa_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doação_has_Produto_Produto1`
    FOREIGN KEY (`Produto_Prod_Cod`)
    REFERENCES `mydb`.`Produto` (`Prod_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Voluntario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Voluntario` (
  `Vol_Cpf` VARCHAR(14) NOT NULL,
  `Vol_Nome` VARCHAR(60) NOT NULL,
  `Vol_Telefone` VARCHAR(20) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `TipoAecsso` INT NOT NULL,
  `Senha` VARCHAR(30) NOT NULL,
  `DataFimVoluntario` DATE NOT NULL,
  `DataInicioVoluntario` DATE NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `CEP` VARCHAR(10) NOT NULL,
  `UserName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Vol_Cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Campanha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Campanha` (
  `idCampanha` INT NOT NULL,
  `Campanha_Descr` VARCHAR(100) NOT NULL,
  `Campanha_DTINI` DATE NOT NULL,
  `Campanha_DTFIM` DATE NOT NULL,
  `CampanhaTotalArrecado` FLOAT NOT NULL,
  `Observacao` VARCHAR(100) NULL,
  `Funcionario_Func_Cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`idCampanha`),
  INDEX `fk_Campanha_Funcionario1_idx` (`Funcionario_Func_Cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Campanha_Funcionario1`
    FOREIGN KEY (`Funcionario_Func_Cpf`)
    REFERENCES `mydb`.`Funcionario` (`Func_Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parametrizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parametrizacao` (
  `idParametrizacao` INT NOT NULL,
  `RazaoSocial` VARCHAR(90) NOT NULL,
  `NomeFantasia` VARCHAR(90) NOT NULL,
  `Telefone` VARCHAR(20) NOT NULL,
  `Site` VARCHAR(60) NOT NULL,
  `Email` VARCHAR(40) NOT NULL,
  `Rua` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `UF` VARCHAR(2) NULL,
  `CEP` VARCHAR(10) NULL,
  `LogotipoSmall` VARCHAR(45) NULL,
  `LogotipoBig` VARCHAR(45) NULL,
  PRIMARY KEY (`idParametrizacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItensDaLista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItensDaLista` (
  `Produto_Prod_Cod` INT NOT NULL,
  `ListaCompra_Lc_Cod` INT NOT NULL,
  `ListaCompra_Funcionario_Func_Cpf` VARCHAR(18) NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Produto_Prod_Cod`, `ListaCompra_Lc_Cod`, `ListaCompra_Funcionario_Func_Cpf`),
  INDEX `fk_Produto_has_ListaCompra_ListaCompra1_idx` (`ListaCompra_Lc_Cod` ASC, `ListaCompra_Funcionario_Func_Cpf` ASC) VISIBLE,
  INDEX `fk_Produto_has_ListaCompra_Produto1_idx` (`Produto_Prod_Cod` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_ListaCompra_Produto1`
    FOREIGN KEY (`Produto_Prod_Cod`)
    REFERENCES `mydb`.`Produto` (`Prod_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_ListaCompra_ListaCompra1`
    FOREIGN KEY (`ListaCompra_Lc_Cod` , `ListaCompra_Funcionario_Func_Cpf`)
    REFERENCES `mydb`.`ListaCompra` (`Lc_Cod` , `Funcionario_Func_Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItensDaListaFornecCotacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItensDaListaFornecCotacao` (
  `ItensDaLista_Produto_Prod_Cod` INT NOT NULL,
  `ItensDaLista_ListaCompra_Lc_Cod` INT NOT NULL,
  `ItensDaLista_ListaCompra_Funcionario_Func_Cpf` VARCHAR(14) NOT NULL,
  `FornecCotacao_Fornecedor_idFornecedor` INT NOT NULL,
  `FornecCotacao_Cotacao_idCotacao` INT NOT NULL,
  `ValorCotacao` FLOAT NOT NULL,
  PRIMARY KEY (`ItensDaLista_Produto_Prod_Cod`, `ItensDaLista_ListaCompra_Lc_Cod`, `ItensDaLista_ListaCompra_Funcionario_Func_Cpf`, `FornecCotacao_Fornecedor_idFornecedor`, `FornecCotacao_Cotacao_idCotacao`),
  INDEX `fk_ItensDaLista_has_FornecCotacao_FornecCotacao1_idx` (`FornecCotacao_Fornecedor_idFornecedor` ASC, `FornecCotacao_Cotacao_idCotacao` ASC) VISIBLE,
  INDEX `fk_ItensDaLista_has_FornecCotacao_ItensDaLista1_idx` (`ItensDaLista_Produto_Prod_Cod` ASC, `ItensDaLista_ListaCompra_Lc_Cod` ASC, `ItensDaLista_ListaCompra_Funcionario_Func_Cpf` ASC) VISIBLE,
  CONSTRAINT `fk_ItensDaLista_has_FornecCotacao_ItensDaLista1`
    FOREIGN KEY (`ItensDaLista_Produto_Prod_Cod` , `ItensDaLista_ListaCompra_Lc_Cod` , `ItensDaLista_ListaCompra_Funcionario_Func_Cpf`)
    REFERENCES `mydb`.`ItensDaLista` (`Produto_Prod_Cod` , `ListaCompra_Lc_Cod` , `ListaCompra_Funcionario_Func_Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItensDaLista_has_FornecCotacao_FornecCotacao1`
    FOREIGN KEY (`FornecCotacao_Fornecedor_idFornecedor` , `FornecCotacao_Cotacao_idCotacao`)
    REFERENCES `mydb`.`FornecCotacao` (`Fornecedor_idFornecedor` , `Cotacao_idCotacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItensCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItensCompra` (
  `Produto_Prod_Cod` INT NOT NULL,
  `Compra_Compra_Cod` INT NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Produto_Prod_Cod`, `Compra_Compra_Cod`),
  INDEX `fk_Produto_has_Compra_Compra1_idx` (`Compra_Compra_Cod` ASC) VISIBLE,
  INDEX `fk_Produto_has_Compra_Produto1_idx` (`Produto_Prod_Cod` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Compra_Produto1`
    FOREIGN KEY (`Produto_Prod_Cod`)
    REFERENCES `mydb`.`Produto` (`Prod_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Compra_Compra1`
    FOREIGN KEY (`Compra_Compra_Cod`)
    REFERENCES `mydb`.`Compra` (`Compra_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SaidaRefeicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SaidaRefeicao` (
  `idSaidaRefeicao` INT NOT NULL,
  `DataRegistro` DATE NOT NULL,
  `Funcionario_Func_Cpf` VARCHAR(14) NOT NULL,
  `Observacao` VARCHAR(100) NULL,
  PRIMARY KEY (`idSaidaRefeicao`),
  INDEX `fk_SaidaRefeicao_Funcionario1_idx` (`Funcionario_Func_Cpf` ASC) VISIBLE,
  CONSTRAINT `fk_SaidaRefeicao_Funcionario1`
    FOREIGN KEY (`Funcionario_Func_Cpf`)
    REFERENCES `mydb`.`Funcionario` (`Func_Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstoqueSaidaRefeicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstoqueSaidaRefeicao` (
  `Estoque_Est_Cod` INT NOT NULL,
  `SaidaRefeicao_idSaidaRefeicao` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Estoque_Est_Cod`, `SaidaRefeicao_idSaidaRefeicao`),
  INDEX `fk_Estoque_has_SaidaRefeicao_SaidaRefeicao1_idx` (`SaidaRefeicao_idSaidaRefeicao` ASC) VISIBLE,
  INDEX `fk_Estoque_has_SaidaRefeicao_Estoque1_idx` (`Estoque_Est_Cod` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_has_SaidaRefeicao_Estoque1`
    FOREIGN KEY (`Estoque_Est_Cod`)
    REFERENCES `mydb`.`Estoque` (`Est_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_has_SaidaRefeicao_SaidaRefeicao1`
    FOREIGN KEY (`SaidaRefeicao_idSaidaRefeicao`)
    REFERENCES `mydb`.`SaidaRefeicao` (`idSaidaRefeicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Campanha_has_Voluntario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Campanha_has_Voluntario` (
  `Campanha_idCampanha` INT NOT NULL,
  `Voluntario_Vol_Cpf` VARCHAR(28) NOT NULL,
  `CargoCampanha` VARCHAR(50) NULL,
  PRIMARY KEY (`Campanha_idCampanha`, `Voluntario_Vol_Cpf`),
  INDEX `fk_Campanha_has_Voluntario_Voluntario1_idx` (`Voluntario_Vol_Cpf` ASC) VISIBLE,
  INDEX `fk_Campanha_has_Voluntario_Campanha1_idx` (`Campanha_idCampanha` ASC) VISIBLE,
  CONSTRAINT `fk_Campanha_has_Voluntario_Campanha1`
    FOREIGN KEY (`Campanha_idCampanha`)
    REFERENCES `mydb`.`Campanha` (`idCampanha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Campanha_has_Voluntario_Voluntario1`
    FOREIGN KEY (`Voluntario_Vol_Cpf`)
    REFERENCES `mydb`.`Voluntario` (`Vol_Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NecessidadeCesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NecessidadeCesta` (
  `PessoaCarente_PC_Cpf` VARCHAR(14) NOT NULL,
  `CestaBasica_CB_Cod` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Quantidade` INT NOT NULL,
  `Observacao` VARCHAR(100) NULL,
  `Funcionario_Func_Cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`PessoaCarente_PC_Cpf`, `CestaBasica_CB_Cod`),
  INDEX `fk_PessoaCarente_has_CestaBasica_CestaBasica1_idx` (`CestaBasica_CB_Cod` ASC) VISIBLE,
  INDEX `fk_PessoaCarente_has_CestaBasica_PessoaCarente1_idx` (`PessoaCarente_PC_Cpf` ASC) VISIBLE,
  INDEX `fk_Necessidade_Funcionario1_idx` (`Funcionario_Func_Cpf` ASC) VISIBLE,
  CONSTRAINT `fk_PessoaCarente_has_CestaBasica_PessoaCarente1`
    FOREIGN KEY (`PessoaCarente_PC_Cpf`)
    REFERENCES `mydb`.`PessoaCarente` (`PC_Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PessoaCarente_has_CestaBasica_CestaBasica1`
    FOREIGN KEY (`CestaBasica_CB_Cod`)
    REFERENCES `mydb`.`CestaBasica` (`CB_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Necessidade_Funcionario1`
    FOREIGN KEY (`Funcionario_Func_Cpf`)
    REFERENCES `mydb`.`Funcionario` (`Func_Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NecessidadeProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NecessidadeProduto` (
  `PessoaCarente_PC_Cpf` VARCHAR(14) NOT NULL,
  `Produto_Prod_Cod` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Quantidade` INT NOT NULL,
  `Observacao` VARCHAR(100) NULL,
  PRIMARY KEY (`PessoaCarente_PC_Cpf`, `Produto_Prod_Cod`),
  INDEX `fk_PessoaCarente_has_Produto_Produto1_idx` (`Produto_Prod_Cod` ASC) VISIBLE,
  INDEX `fk_PessoaCarente_has_Produto_PessoaCarente1_idx` (`PessoaCarente_PC_Cpf` ASC) VISIBLE,
  CONSTRAINT `fk_PessoaCarente_has_Produto_PessoaCarente1`
    FOREIGN KEY (`PessoaCarente_PC_Cpf`)
    REFERENCES `mydb`.`PessoaCarente` (`PC_Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PessoaCarente_has_Produto_Produto1`
    FOREIGN KEY (`Produto_Prod_Cod`)
    REFERENCES `mydb`.`Produto` (`Prod_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DoaçãoNecessidadeProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DoaçãoNecessidadeProduto` (
  `Doação_Doa_Cod` INT NOT NULL,
  `NecessidadeProduto_PessoaCarente_PC_Cpf` VARCHAR(18) NOT NULL,
  `NecessidadeProduto_Produto_Prod_Cod` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Doação_Doa_Cod`, `NecessidadeProduto_PessoaCarente_PC_Cpf`, `NecessidadeProduto_Produto_Prod_Cod`),
  INDEX `fk_Doação_has_NecessidadeProduto_NecessidadeProduto1_idx` (`NecessidadeProduto_PessoaCarente_PC_Cpf` ASC, `NecessidadeProduto_Produto_Prod_Cod` ASC) VISIBLE,
  INDEX `fk_Doação_has_NecessidadeProduto_Doação1_idx` (`Doação_Doa_Cod` ASC) VISIBLE,
  CONSTRAINT `fk_Doação_has_NecessidadeProduto_Doação1`
    FOREIGN KEY (`Doação_Doa_Cod`)
    REFERENCES `mydb`.`Doação` (`Doa_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doação_has_NecessidadeProduto_NecessidadeProduto1`
    FOREIGN KEY (`NecessidadeProduto_PessoaCarente_PC_Cpf` , `NecessidadeProduto_Produto_Prod_Cod`)
    REFERENCES `mydb`.`NecessidadeProduto` (`PessoaCarente_PC_Cpf` , `Produto_Prod_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DoaçãoNecessidadeCesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DoaçãoNecessidadeCesta` (
  `Doação_Doa_Cod` INT NOT NULL,
  `NecessidadeCesta_PessoaCarente_PC_Cpf` VARCHAR(18) NOT NULL,
  `NecessidadeCesta_CestaBasica_CB_Cod` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Doação_Doa_Cod`, `NecessidadeCesta_PessoaCarente_PC_Cpf`, `NecessidadeCesta_CestaBasica_CB_Cod`),
  INDEX `fk_Doação_has_NecessidadeCesta_NecessidadeCesta1_idx` (`NecessidadeCesta_PessoaCarente_PC_Cpf` ASC, `NecessidadeCesta_CestaBasica_CB_Cod` ASC) VISIBLE,
  INDEX `fk_Doação_has_NecessidadeCesta_Doação1_idx` (`Doação_Doa_Cod` ASC) VISIBLE,
  CONSTRAINT `fk_Doação_has_NecessidadeCesta_Doação1`
    FOREIGN KEY (`Doação_Doa_Cod`)
    REFERENCES `mydb`.`Doação` (`Doa_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doação_has_NecessidadeCesta_NecessidadeCesta1`
    FOREIGN KEY (`NecessidadeCesta_PessoaCarente_PC_Cpf` , `NecessidadeCesta_CestaBasica_CB_Cod`)
    REFERENCES `mydb`.`NecessidadeCesta` (`PessoaCarente_PC_Cpf` , `CestaBasica_CB_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
